# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# .-----------------------------------------------------------------------------. #
# |                                                                             | #
# |          _______   _                       _   ____                         | #
# |         |__   __| | |                     | | |  _ \                        | #
# |            | | ___| | ___ _ __   ___  _ __| |_| |_) | _____      __         | #
# |            | |/ _ \ |/ _ \ '_ \ / _ \| '__| __|  _ < / _ \ \ /\ / /         | #
# |            | |  __/ |  __/ |_) | (_) | |  | |_| |_) | (_) \ V  V /          | #
# |            |_|\___|_|\___| .__/ \___/|_|   \__|____/ \___/ \_/\_/           | #
# |                          | |                                                | #
# |                          |_|                                                | #
# |                                                                             | #
# '-----------------------------------------------------------------------------' #
#                                                                                 #
#   Developed:                   My profile page:                                 #
#   By SadShrimpy#9190 with <3 - https://www.spigotmc.org/members/shiry.583821/   #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Do not modify this value, it may CORRUPT the entire config file!
version: v1.0-Relase

magic-bow:
  name: "&dMagic &6Fantastic &bBow"
  lore:
    - "&7Hm...."
    - "&7Maybe I should try to"
    - "&eshoot &7an arrow..."
  unbreakable: true